version: '3'
services:
  db:
    environment:
      - .env
    image: mysql
  web:
    build: .
    command: rails s -p 3003 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3003:3003"
    depends_on:
      - db