version: '3'
services:
  db:
    image: mysql
    ports:
      - "5306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
  web:
    build: .
    command: bundle exec rails s -p 3003 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3003:3003"
    depends_on:
      - db
